### ISSUE TITLE
Erro ao rodar aplicação depois do build

### ISSUE THREAD

**Issue by andersondn** [carlos-levir/Electron-Todo-App#4]
A aplicação funciona normalmente em mode de desenvolvimento, porém ao realizar o build e rodar o app é exibido o seguinte error:
Error: Cannot find module ‘../app’

(Teste realizado no MacOs Catalina 10.15.3)

**Comment by CarlosLevir** [comment]
Opa @andersondn, o que aconteceu foi uma incompatibilidade com o sistema de 32 bits que não é suportado pelo mac os catalina.
Está consertado agora ;)
